Add evm-bully=yes build to CI
aurora-is-near/aurora-engine pull request #121
Opened 2021-06-03 05:44 UTC by frankbraun

The contract build for the evm-bully (`make evm-bully=yes`) often breaks.
Add it to CI to prevent that from happening.

2021-06-03 11:44 UTC, sept-en approved these changes
LGTM!

I also think that we should use `develop` as a base branch having the release protocol we have. I.e. the `master` points to the latest deployed version and the `develop` branch is the latest stable one that will be uploaded into `master` and released after that.

2021-06-03 13:43 UTC, artob requested changes
This should be targeted at `develop`, not `master`. And there are copy-paste artifacts to remove.

2021-06-03 13:43 UTC, artob commented on .github/workflows/builds.yml
> +      - name: Update the latest tag
You need to remove the `Update the latest release` and `Update the latest tag` steps, lest you introduce a race condition for updating the `latest` tag.

In addition, it is also unlikely that you actually need the `Upload the release.wasm artifact` step (which also wasn't properly renamed).

2021-06-04 02:22 UTC, frankbraun commented
I changed it to target `develop` instead of `master`. Also moved the tests over to `tests.yml`, because this should be checked on every PR, not just for releases.

2021-06-04 08:54 UTC, artob approved these changes

2021-06-04 08:55 UTC, merged