Fix: Makefile
aurora-is-near/aurora-engine pull request #25
Opened 2021-04-07 15:08 UTC by birchmd

* `make check` includes running tests, running `clippy`, checking the code formatting
* `make test` depends on release since it needs the `release.wasm` artifact

2021-04-07 17:05 UTC, joshuajbouw requested changes
clippy & check on nightly catches quite a bit more than what is on stable right now. I would highly suggest that we do use it `+nightly`

2021-04-07 17:35 UTC, birchmd commented
@joshuajbouw  I'll add `+nightly` because it doesn't hurt either way. But just to confirm for myself, shouldn't the nightly `fmt` and `clippy` be used as is because that is what is specified in the `rust-toolchain` file?

2021-04-07 17:39 UTC, birchmd commented
Actually, I'll hold off on adding `+nightly` because I think it overrides the toolchain specified in `rust-toolchain`, which I don't think is what we want. @joshuajbouw let me know if you think differently.

2021-04-08 02:44 UTC, joshuajbouw commented
Ah right, I missed the rust-toolchain file there. Well noted. @birchmd

2021-04-08 02:44 UTC, joshuajbouw approved these changes
Looks good

2021-04-08 02:47 UTC, joshuajbouw requested changes
Sorry, flipping back to request changes, just waking up and a bit bleary eyed. I do really believe that clippy & check should be latest nightly and not part of the locked toolchain due to the extra lint checks you get which can improve code quality further.

2021-04-08 14:26 UTC, birchmd commented
Thanks @joshuajbouw always happy to assist in the pursuit of better code. `+nightly` added in https://github.com/aurora-is-near/aurora-engine/pull/25/commits/fe10b5ec12d8d8fd0ac04d32db111cd273be1780

One thing I'd like you to clarify for my own understanding is how the `nightly` toolchain works. When I run `cargo +nightly clippy` does it automatically find and use the latest `clippy` build, or will I need to manually update my local `nightly` toolchain occasionally?

2021-04-08 15:57 UTC, joshuajbouw commented
Right, we already discussed this privately. You would need to manually update your local nightly toolchain.

2021-04-08 15:58 UTC, joshuajbouw approved these changes
Happy with this.

2021-04-12 15:45 UTC, merged

2021-04-12 15:48 UTC, artob approved these changes

2021-04-12 15:48 UTC, artob commented on Makefile
> +
New targets like these need to be added to the `.PHONY` line as well.

2021-04-12 15:50 UTC, artob commented on Makefile
> +
Fixed in 34d247a.

2021-04-12 15:52 UTC, artob commented
> I do really believe that clippy & check should be latest nightly and not part of the locked toolchain due to the extra lint checks you get which can improve code quality further.

I've merged the dependency on current nightly for now, but depending on how much that slows down our CI cycle we may need to revert that bit. (It was dog slow as it was.)

2024-10-28 21:47 UTC, mrLSD approved these changes