Feat(benchmarks): update gas bounds after wasm cost reduction
aurora-is-near/aurora-engine pull request #406
Opened 2021-12-23 08:56 UTC by mrLSD

NEAR is reducing the wasm cost again: near/nearcore#5365

Revisited our gas usage regression tests with the new bounds.

Related to: #380

2022-01-03 13:17 UTC, birchmd requested changes

2022-01-03 13:17 UTC, birchmd commented on engine-tests/src/tests/one_inch.rs
> +    assert!(result.gas_used >= 2_000); // more than 302k EVM gas used
This doesn't look right. The EVM gas usage shouldn't change.

2022-01-03 13:17 UTC, birchmd commented on engine-tests/src/tests/uniswap.rs
>      test_utils::assert_gas_bound(profile.all_gas(), 68);
Need to change this as well

2022-01-03 13:17 UTC, birchmd commented on engine-tests/src/tests/uniswap.rs
>      test_utils::assert_gas_bound(profile.all_gas(), 114);
Need to change this as well

2022-01-03 13:17 UTC, birchmd commented on engine-tests/src/tests/one_inch.rs
>      // at least 70% of which is from wasm execution
Should update comment. Also need to change the line above this (`assert_gas_bound`)

2022-01-04 19:49 UTC, birchmd approved these changes
LGTM

2022-01-06 16:58 UTC, joshuajbouw approved these changes

2022-01-06 17:12 UTC, merged