Fix near-blake2 dependency
aurora-is-near/aurora-engine pull request #484
Opened 2022-04-06 16:00 UTC by mrLSD

Issue related to `blake2_f` function compatibility.

Related to:
* [EIP-152](https://eips.ethereum.org/EIPS/eip-152)
* [Blake2 RFC-7693](https://datatracker.ietf.org/doc/html/rfc7693#section-3.2)

Realted to *EIP-152* `compress` function should accept parameters: `h, m, t, f`

2022-04-08 12:17 UTC, joshuajbouw requested changes
While this does work, do remember the discussion we had and the requirements that we should have aurora-blake2 to be that commit, then we use our own library for that.

2022-04-08 12:31 UTC, mrLSD commented
At the moment after the research, it became obvious that the `compress` upstream `blake2` function does not meet the requirements for `EIP-152`.
What does it mean:
* We can't directly set parameters: `h, m, t, f`
* We can't set the `round` parameter
* Implementation looks like a "black box" - if we compare m with the reference implementation of `[Blake2 RFC-7693](https://datatracker.ietf.org/doc/html/rfc7693#section-3.2)`

`near-blake2` (exact commit) solve that issue.

2022-04-08 14:12 UTC, joshuajbouw commented
As we had discussed yeah, it's quite a bit unfortunate. The RFC is actually intended to be quite open. It is always scary to have to alter a cryptographic function to fit a requirement :S. Would be good to point that out to the authors, and figure out a way forward.

2022-04-15 09:07 UTC, joshuajbouw requested changes

2022-04-15 09:07 UTC, joshuajbouw commented on engine-precompiles/Cargo.toml
> +near-blake2 = { git = "https://github.com/near/near-blake2.git", rev = "cebb7df79608a7058017940830d37c37d55d21fe", default-features = false }
This needs to be changed to Aurora's

2022-04-25 14:36 UTC, artob commented
Task linked: [CU-290q9nc Engine v1.5.2](https://app.clickup.com/t/290q9nc)

2022-04-25 14:36 UTC, artob commented
Task linked: [CU-290q9nc Engine v1.5.2](https://app.clickup.com/t/290q9nc)

2022-04-26 12:12 UTC, joshuajbouw approved these changes

2022-04-26 12:27 UTC, merged