Add serde for TraceTransaction
aurora-is-near/aurora-engine pull request #495
Opened 2022-04-27 15:49 UTC by mfornet

This is required for borealis-engine as the base branch.

It was really unfortunate that OpCode didn't provide serde, even if it is just a single `u8`. I implemented custom de/serialization methods. If you have any simpler way, let me know.

2022-04-27 16:43 UTC, birchmd approved these changes
Looks good to me.
I can't find a good way to avoid the `Opcode` boilerplate either.
I think you also need to push an update to `Cargo.lock` (when I compile locally the file changes).

2022-04-28 07:05 UTC, joshuajbouw requested changes

2022-04-28 07:05 UTC, joshuajbouw commented on engine-standalone-tracing/src/types.rs
> +mod opcode_serde {
Yes, it should have it.

2022-04-28 09:32 UTC, mfornet commented on engine-standalone-tracing/src/types.rs
> +mod opcode_serde {
Added, and updated Cargo.lock

2022-05-02 13:34 UTC, merged