Constant errors
aurora-is-near/aurora-engine pull request #535
Opened 2022-06-21 09:04 UTC by mrLSD

Set errors as constant messages with separated modules for crates

## Reason
* Avoid duplication of error messages and reduce binary size.
* Organize for more convenient way to manage error messages

2022-06-23 21:09 UTC, joshuajbouw requested changes

2022-06-23 21:09 UTC, joshuajbouw commented on engine/src/errors.rs
> +
Can you fix the spacing on all these please?

2022-06-23 23:59 UTC, sept-en commented
As the refactoring is being made, IMO it'd be good to separate these errors into submodules: e.g. `errors::evm::ERR_OUT_OF_GAS`, `errors:json::ERR_NOT_A_JSON_TYPE`, etc.

WDYT @joshuajbouw ?

2022-06-24 07:08 UTC, mrLSD commented
> As the refactoring is being made, IMO it'd be good to separate these errors into submodules: e.g. `errors::evm::ERR_OUT_OF_GAS`, `errors:json::ERR_NOT_A_JSON_TYPE`, etc.
> 
> WDYT @joshuajbouw ?

@sept-en AFAIK main idea was deduplication.
Your proposal is good as a logical separation. But we can't guarantee in that case deduplication error messages.

After splitting error messages as separated module `errors` we almost do not have benefits with bin size.
But after that, a lot of error messages were deduplicated. And I think it is good.

2022-06-27 12:39 UTC, Aurora-ClickUp commented
Task linked: [CU-2g5nvuc The binary size can be reduced by using constants for error messages.](https://app.clickup.com/t/2g5nvuc)

2022-06-27 16:22 UTC, joshuajbouw commented
@sept-en I think its a good idea for the future, but not right now. We got to focus on some more higher importance matters.

2022-07-01 09:11 UTC, joshuajbouw approved these changes

2022-07-01 10:08 UTC, joshuajbouw commented
Please fix conflicts.

2022-07-04 10:56 UTC, merged

2022-07-04 23:00 UTC, sept-en commented
Created #547 to ensure we track possible future refactoring somewhere