Chore: security workflow
aurora-is-near/aurora-engine pull request #643
Opened 2022-11-28 13:38 UTC by vzctl

This PR adds Backstage information for additional components and enables Clippy/Slither checks using the shared github workflow.

2022-12-21 09:33 UTC, joshuajbouw requested changes

2022-12-21 09:33 UTC, joshuajbouw commented on engine-standalone-storage/.catalog-info.yaml
> +    aurora.dev/security-tier: "-1"
Make this a 2.

2022-12-21 09:33 UTC, joshuajbouw commented on engine-standalone-tracing/.catalog-info.yaml
> +    aurora.dev/security-tier: "-1"
Make this a 2.

2022-12-21 09:33 UTC, joshuajbouw commented on engine-transactions/.catalog-info.yaml
> +    aurora.dev/security-tier: "-1"
This is a 1.

2022-12-23 10:49 UTC, aleksuss approved these changes

2022-12-23 10:49 UTC, merged