Fix: miscellaneous minor issues
aurora-is-near/aurora-engine pull request #738
Opened 2023-04-03 13:42 UTC by 0x3bfc

2023-04-03 14:40 UTC, aleksuss requested changes

2023-04-03 14:40 UTC, aleksuss commented on engine/src/connector.rs
> +                let eth_amount = Wei::new(U256::from(args.amount.as_u128()))
```suggestion
                let eth_amount = Wei::new_u128(args.amount.as_u128())
```

2023-04-04 08:23 UTC, aleksuss commented on engine-precompiles/src/promise_result.rs
> +                cost = cost
I would recommend using here `ExitError::Other(Borrowed("ERR_OVERFLOW_NUMBER"))`.

2023-04-04 12:37 UTC, aleksuss commented on engine-precompiles/src/secp256k1.rs
> +#[allow(unused_imports)]
```suggestion
cfg(not(feature = "contract"))]
```

2023-04-05 10:05 UTC, mandreyel approved these changes

2023-04-05 10:17 UTC, mrLSD approved these changes

2023-04-05 13:02 UTC, merged