chore: add build flow fow xcc-router
aurora-is-near/aurora-engine pull request #744
Opened 2023-04-18 14:22 UTC by aleksuss

## Description

## Performance / NEAR gas cost considerations

## Testing

## How should this be reviewed

## Additional information

2023-04-18 14:38 UTC, birchmd requested changes

2023-04-18 14:38 UTC, birchmd commented on Makefile.toml
> +env = { "RUSTFLAGS" = "-C strip=symbols --remap-path-prefix ${HOME}=/path/to/home/ --remap-path-prefix ${PWD}=/path/to/source/", "CARGO_FEATURES" = "${CARGO_FEATURES_BUILD}", "RELEASE" = "--release",
We should add the additional flag `-C link-arg=-s`. This is important to keep the size of the contract small. If the contract is too large then the 2 wNEAR fee we charge to create an XCC account will not be enough to cover the storage cost. The compiled contract size should be less than 150 kB.

2023-04-18 15:30 UTC, birchmd approved these changes
Nice work!

2023-04-19 06:48 UTC, joshuajbouw approved these changes

2023-04-19 06:49 UTC, joshuajbouw commented
Note, that the push to master is intentional.

2023-05-11 10:41 UTC, merged

2023-12-27 21:26 UTC, mrLSD approved these changes