Merge/joshuajbouw/2.9.0 develop
aurora-is-near/aurora-engine pull request #754
Opened 2023-05-09 07:18 UTC by joshuajbouw

## Description

Merges `master` branch for 2.9.0 to `develop`.

2023-05-09 07:40 UTC, aleksuss requested changes
It seems that the `Cargo.lock` file is corrupted.

2023-05-11 10:45 UTC, aleksuss approved these changes

2023-05-11 11:30 UTC, aleksuss commented
Also, this PR has changed the mechanism of publishing new releases. After merging this PR, new releases will be published after pushing a new tag rather than pushing into the master branch.

2023-05-11 12:16 UTC, merged

2023-12-17 21:05 UTC, mrLSD approved these changes