Feat> wasm-opt and refactored gas cost tests
aurora-is-near/aurora-engine pull request #835
Opened 2023-09-07 13:40 UTC by mrLSD

## Description

## Performance / NEAR gas cost considerations

## Testing

## How should this be reviewed

## Additional information

2023-09-07 14:21 UTC, mrLSD commented
Related to #818

2023-09-07 14:54 UTC, aleksuss requested changes

2023-09-07 14:57 UTC, aleksuss commented
Also, we need to modify building artifacts [script](https://github.com/aurora-is-near/aurora-engine/blob/develop/.github/workflows/builds.yml).

2023-09-07 15:21 UTC, birchmd reviewed
Cool! Nice to see low-hanging fruit like this giving a performance improvement.

We will probably also need to update the README or something to say that wasm-opt is now a required tool for building the project.

2023-09-08 12:51 UTC, birchmd approved these changes

2023-09-13 08:54 UTC, aleksuss approved these changes

2023-09-14 10:46 UTC, aleksuss commented
@mrLSD, why don't we use `wasm-opt` for `xcc-router` smart contract?

2023-09-14 13:03 UTC, mrLSD commented
> @mrLSD, why don't we use `wasm-opt` for `xcc-router` smart contract?

Because it's not part of the test-flow:
```
[tasks.test-flow]
category = "Test"
dependencies = [
    "build-test",
    "test-contracts",
    "test-workspace",
    "bench-modexp",
]
```

2025-04-23 11:02 UTC, aleksuss commented
I also want to note that applying the `wasm-opt` utility for the contract file resolves the deserialisation error if the contract is built with Rust > 1.81.0. That is precisely how the `cargo-near` crate resolves the issue.
```
 --no-wasmopt
          Do not run equivalent of `wasm-opt -O` on the generated output as a post-step
          
          This `wasm-opt -O` step is required for correctness of build on rustc >= 1.82.
          Otherwise, if the post-step is skipped, nearcore runtime won't be able to parse and validate deployed wasm.
          In these cases a `CompilationError(PrepareError(Deserialization))` is expected to be emitted
          when performing calls to wasm with unsupported features.
```

2025-04-23 11:05 UTC, merged