feat: add api to get ft balances for multiple accounts
aurora-is-near/aurora-engine pull request #905
Opened 2024-02-21 00:52 UTC by karim-en

## Description
The PR adds a public method to the engine/internal connector to get balances of multiple accounts. This is needed because we have changed the migration logic to migrate the balances based on the on-chain data, not off-chain.

## Performance / NEAR gas cost considerations
The borsh is used instead of JSON to decrease gas usage and migrate more accounts in one batch.

## Testing
Added a test to the crate `aurora-engine-tests`, not `aurora-engine-tests-connector` because the second one is enabled just for silo builds.

## How should this be reviewed

## Additional information
It's controversial whether to use `HashMap<AccountId, Balance>` or `Vec<(AccountId, Balance)>`; the `HashMap` prevents duplication, but on the other side, it increases gas usage.

2024-02-26 10:53 UTC, aleksuss requested changes

2024-02-26 10:53 UTC, aleksuss commented on engine/src/contract_methods/connector/internal.rs
> +        self.io.return_output(&balances.try_to_vec().unwrap());
Borsh has been bumped to 1.x.x.
```suggestion
        self.io.return_output(&borsh::to_vec(&balances).unwrap());
```

2024-02-26 11:08 UTC, aleksuss commented
> It's controversial whether to use HashMap<AccountId, Balance> or Vec<(AccountId, Balance)>; the HashMap prevents duplication, but on the other side, it increases gas usage.

I guess we can use the `HashMap` and don't care about the gas usage since it will be invoked only once.

2024-02-26 12:57 UTC, birchmd approved these changes

2024-02-27 14:30 UTC, aleksuss commented on engine/src/contract_methods/connector/internal.rs
> +    pub fn ft_balances_of(&mut self, accounts: Vec<AccountId>) {
It's needed because the `return_output` method requires a mutable reference to the `IO`.

2024-02-27 14:31 UTC, birchmd commented on engine/src/contract_methods/connector/internal.rs
> +    pub fn ft_balances_of(&mut self, accounts: Vec<AccountId>) {
Ah, got it, thanks.

2024-02-27 14:32 UTC, merged

2024-02-27 14:37 UTC, mrLSD approved these changes